#!/usr/bin/env bash
# Render or verify security/switches-reference.md from switches.json.
set -uo pipefail

plugin_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)"
input="$plugin_root/ai-engineering/bootstrap/switches.json"
output="$plugin_root/security/switches-reference.md"
mode=""
jq_bin="jq"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check|--update)
      [ -z "$mode" ] || { printf 'ERROR: choose exactly one mode\n' >&2; exit 2; }
      mode="${1#--}"
      shift
      ;;
    --input)
      [ "$#" -ge 2 ] || { printf 'ERROR: --input requires a path\n' >&2; exit 2; }
      input="$2"
      shift 2
      ;;
    --output)
      [ "$#" -ge 2 ] || { printf 'ERROR: --output requires a path\n' >&2; exit 2; }
      output="$2"
      shift 2
      ;;
    --jq)
      [ "$#" -ge 2 ] || { printf 'ERROR: --jq requires a command\n' >&2; exit 2; }
      jq_bin="$2"
      shift 2
      ;;
    *) printf 'ERROR: unknown argument: %s\n' "$1" >&2; exit 2 ;;
  esac
done

[ -n "$mode" ] || { printf 'ERROR: pass --check or --update\n' >&2; exit 2; }
[ -n "$input" ] && [ -f "$input" ] || { printf 'ERROR: missing input: %s\n' "$input" >&2; exit 1; }
[ -n "$output" ] || { printf 'ERROR: output path is empty\n' >&2; exit 1; }

if case "$jq_bin" in */*) [ -x "$jq_bin" ] ;; *) command -v "$jq_bin" >/dev/null 2>&1 ;; esac; then
  :
else
  printf 'ERROR: jq is required: %s\n' "$jq_bin" >&2
  exit 1
fi

# Validate both JSON syntax and the switch schema before creating any output.
if ! "$jq_bin" -e '
  type == "object" and
  (.switches | type == "array") and
  (.switches | length > 0) and
  all(.switches[];
    type == "object" and
    (.id | type == "string" and length > 0) and
    (.default | type == "boolean") and
    (.category | type == "string" and length > 0) and
    (.summary | type == "string" and length > 0) and
    (.description | type == "string" and length > 0) and
    (.policy_ref | type == "string" and length > 0) and
    (.introduced_in | type == "string" and test("^[0-9]+\\.[0-9]+\\.[0-9]+$")) and
    (.settings_json_patch == null or
      ((.settings_json_patch | type) == "object" and
       (.settings_json_patch.pointer | type == "string" and startswith("/")) and
       (.settings_json_patch | has("value"))))
  ) and
  ((.switches | map(.id) | unique | length) == (.switches | length))
' "$input" >/dev/null 2>&1; then
  printf 'ERROR: invalid switches JSON or schema: %s\n' "$input" >&2
  exit 1
fi

output_dir="$(dirname -- "$output")"
[ -d "$output_dir" ] && [ ! -L "$output_dir" ] \
  || { printf 'ERROR: output directory is unavailable: %s\n' "$output_dir" >&2; exit 1; }
if [ -e "$output" ] && { [ -L "$output" ] || [ ! -f "$output" ]; }; then
  printf 'ERROR: output must be a regular file: %s\n' "$output" >&2
  exit 1
fi

if [ "$mode" = "check" ]; then
  # Check mode is read-only. Render outside the source tree so verification also
  # works when the checkout or generated file directory is intentionally
  # read-only (for example in a packaged plugin or sandboxed release gate).
  rendered="$(mktemp "${TMPDIR:-/tmp}/arkira-switches-reference.XXXXXX" 2>/dev/null)" \
    || { printf 'ERROR: cannot create temporary render file\n' >&2; exit 1; }
else
  # Update mode renders beside the destination so the final rename is atomic on
  # the destination filesystem.
  rendered="$(mktemp "$output_dir/.switches-reference.XXXXXX" 2>/dev/null)" \
    || { printf 'ERROR: cannot create render file in %s\n' "$output_dir" >&2; exit 1; }
fi
entries="$(mktemp "${TMPDIR:-/tmp}/arkira-switches.XXXXXX" 2>/dev/null)" || {
  rm -f "$rendered"
  printf 'ERROR: cannot create temporary entry file\n' >&2
  exit 1
}
cleanup_generator() {
  [ -z "$rendered" ] || rm -f "$rendered" 2>/dev/null
  [ -z "$entries" ] || rm -f "$entries" 2>/dev/null
}
trap cleanup_generator EXIT HUP INT TERM

if ! "$jq_bin" -r '
  .switches[] |
  [
    .id,
    (.default | tostring),
    .introduced_in,
    .policy_ref,
    .description,
    (if .settings_json_patch == null then "no" else "yes" end),
    (if .settings_json_patch == null then "" else .settings_json_patch.pointer end),
    (if .settings_json_patch == null then "" else (.settings_json_patch.value | tojson) end)
  ] | @tsv
' "$input" > "$entries" 2>/dev/null; then
  printf 'ERROR: jq render failed\n' >&2
  exit 1
fi

if ! {
  printf '# Arkira Switches Reference\n\n'
  printf 'This document mirrors `ai-engineering/bootstrap/switches.json` in human-readable form. Run `/arkira-init` to set any of these. Run `/arkira-update` to pick up new switches added in later plugin versions.\n\n'
  printf 'Auto-generated by `ai-engineering/bootstrap/generate-switches-reference.sh`. Do not edit by hand; edit `switches.json` and re-run the generator.\n'

  while IFS=$'\t' read -r id default introduced policy description has_patch pointer value; do
    [ -n "$id" ] || exit 1
    default_label="off"
    [ "$default" = "true" ] && default_label="on"
    policy_base="$(basename -- "$policy")"
    policy_dir="$(dirname -- "$policy")"
    policy_link="./$policy_base"
    if [ "$policy_dir" != "." ] && [ "$policy_dir" != "security" ]; then
      policy_link="../$policy"
    fi
    printf '\n## %s\n\n' "$id"
    printf '**Default:** %s\n' "$default_label"
    printf '**Introduced in:** %s\n' "$introduced"
    printf '**Policy:** [%s](%s)\n\n' "$policy_base" "$policy_link"
    printf '%s\n\n' "$description"
    if [ "$has_patch" = "yes" ]; then
      printf 'Settings.json effect: sets `%s` to `%s`.\n' "$pointer" "$value"
    else
      printf 'Advisory only; no settings.json effect.\n'
    fi
  done < "$entries"
} > "$rendered"; then
  printf 'ERROR: render failed\n' >&2
  exit 1
fi

[ -s "$rendered" ] && grep -q '^# Arkira Switches Reference$' "$rendered" \
  || { printf 'ERROR: rendered reference failed validation\n' >&2; exit 1; }
chmod 644 "$rendered" 2>/dev/null || { printf 'ERROR: cannot set rendered file mode\n' >&2; exit 1; }

if [ "$mode" = "check" ]; then
  [ -f "$output" ] || { printf 'FAIL: generated reference is missing: %s\n' "$output" >&2; exit 1; }
  if cmp -s "$rendered" "$output"; then
    printf 'PASS %s is current\n' "$output"
    exit 0
  fi
  printf 'FAIL: generated reference is out of date: %s\n' "$output" >&2
  exit 1
fi

if ! mv "$rendered" "$output" 2>/dev/null; then
  printf 'ERROR: atomic output replacement failed: %s\n' "$output" >&2
  exit 1
fi
rendered=""
printf 'UPDATED %s\n' "$output"
exit 0
